# Generated by Django 4.2.11 on 2024-03-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Локация')),
                ('categories', models.CharField(max_length=50, verbose_name='Категория')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
            ],
        ),
    ]
